name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change if your source branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build -- --mode production

      # ✅ Create CNAME file for custom domain
      - name: Add CNAME
        run: echo "markelotone.com" > ./dist/CNAME

      # ✅ Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }} # PAT secret
          publish_dir: ./dist # Adjust if build outputs elsewhere
          publish_branch: gh-pages # ✅ Deployment branch
